#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    enable_guicolors = true
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    filetree_direction = "left"
    relativenumber = false

[[layers]]
  name = "debug"

[[layers]]
  name = "autocomplete"

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "shell"
  default_position = "top"
  default_height = 30

[[layers]]
  name="lang#go"

[[layers]]
  name="fzf"

[[layers]]
  name = "incsearch"

[[layers]]
  name = "format"
  format_on_save = true

[[layers]]
  name = "git"

